P-S4/P1/P1/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
urlpatterns = [
    path('', views.dashboard, name='home'),
    path('admin/', admin.site.urls),
    path('permission_denied/', views.permission_denied, name='permission_denied'),
    path('teacher/', include('Teacher.urls', namespace='teacher')),
    path('class/', include('Class.urls')),
    path('student/', include('Student.urls')),
    path('schedule/', include('Schedule.urls')),
    path('attendance/', include('Attendance.urls')),
    path('rate/', include('Rate.urls')),
    path('user/', include('User.urls')),
    path('predict/', include('Predict.urls')),
]

P-S4/P1/Predict/urls.py
from django.urls import path, include
from . import views

app_name = "Predict"
urlpatterns = [
    path('', views.choose, name='choose'),
    path('<slug:id>', views.predictionOne, name='prediction-one'),
]

P-S4/P1/Schedule/urls.py
from django.urls import path, include
from . import views

app_name = "Schedule"
urlpatterns = [
    path('', views.read, name='read'),
    path('list_attendance/<slug:id>',
         views.list_attendance, name='list_attendance'),
    path('create', views.create, name='create'),
    path('update/<slug:id>', views.update, name='update'),
    path('delete/<slug:id>', views.delete, name='delete'),
    path('<slug:id>', views.readDetail, name='read-detail'),
]

P-S4/P1/Predict/models.py
from django.db import models

# Create your models here.


class Predict(models.Model):
    class Meta:
        # Definisikan kombinasi unik dari tabel_a dan tabel_b untuk mencegah duplikat
        permissions = (
            ('predict_one', 'can predict one student'),
            ('predict_all', 'can predict all student'),
        )

P-S4/P1/Predict/views.py
# Create your views here.
from sklearn.tree import DecisionTreeClassifier
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponse, JsonResponse
from django.contrib import messages
from Student.models import Student, Class, CHOICESGENDER
from Attendance.models import Attendance
from Rate.models import Rate, CHOICESRATE
from Teacher.models import Teacher
from Class.models import Class
# Create your views here.
import joblib
import statistics
import os
CHOICEDISTANCE = [(0, 0), (5, 1), (15, 2)]
CHOICEDISTANCE_AS_CATEGORIES = [(0, "Dekat"), (1, "Sedang"), (2, "Jauh")]
RESULT = [(0, "Sangat Suka"), (1, "Lumayan Suka"), (2, "Tidak Suka")]
TEACHER = [("Misterboy", 0), ("Yanti", 1), ("Greece", 2)]
MODEL_DIRECTORY = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), 'models')


@login_required(login_url="User:login")
@permission_required('Predict.predict_one', login_url="permission_denied")
def predictionOne(request, id):
    try:
        # Cek ada data siswa ga
        nameStudent = Student.objects.get(id=id).name

        if not Attendance.objects.filter(id_student=id).exists():
            raise Attendance.DoesNotExist

        # Cek ada data absensi ga
        dataAttendance = list(Attendance.objects.filter(
            id_student=id).values_list('id', flat=True))

        # Cek ada data rate ga
        dataRate = list(Rate.objects.values_list(
            'id_attendance', flat=True))

        def boolRate(dataRate, dataAttendance):
            for n in dataRate:
                if n in dataAttendance:
                    return True
            raise Rate.DoesNotExist
        boolRate(dataRate, dataAttendance)

        data = list(Student.objects.filter(id=id).values())
        for n in data:
            for m in CHOICEDISTANCE:
                if n['distance'] >= m[0]:
                    distance = m[1]

        data = list(Student.objects.filter(
            id=id).values())
        for n in data:
            class_id = n['id_class_id']
            dataClass = list(Class.objects.filter(id=class_id).values())

            for m in dataClass:
                teacher_id = m['id_teacher_id']
                teacher_name = Teacher.objects.get(id=teacher_id).name

        for n in TEACHER:
            if n[0] == teacher_name:
                teacher = n[1]

        dataAbsent = int(Attendance.objects.filter(
            id_student=id, status_attendance=0).values().count())
        dataPresent = int(Attendance.objects.filter(
            id_student=id, status_attendance=1).values().count())
        persentange_attendance = dataPresent / (dataAbsent+dataPresent)

        data = list(Attendance.objects.filter(
            id_student=id).values_list('id', flat=True))
        result = (list(Rate.objects.filter(
            id_attendance__in=data).values_list('rate', flat=True)))
        rate = round(statistics.mean(result))

        ml_model = joblib.load('ml_model/model3.joblib')
        result = ml_model.predict(
            [[distance, persentange_attendance, rate, teacher]])

        # return HttpResponse(result)
        for n in RESULT:
            if n[0] == result:
                result = n[1]
        return JsonResponse([distance, persentange_attendance, rate, teacher, result], safe=False)

    except Student.DoesNotExist as error:
        return HttpResponse(f"please make student data")
    except Attendance.DoesNotExist as error:
        return HttpResponse(f"please make attendance data")
    except Rate.DoesNotExist as error:
        return HttpResponse(f"please make rate data")


def prediction(id):
    try:
        # Cek ada data siswa ga
        dataStudent = Student.objects.get(id=id)

        ###################### buat data  distance ###############################
        data = list(Student.objects.filter(id=id).values())
        for n in data:
            for m in CHOICEDISTANCE:
                if n['distance'] >= m[0]:
                    distance = m[1]

        ######################## buat data teacher ###############################
        data = list(Student.objects.filter(
            id=id).values())
        for n in data:
            class_id = n['id_class_id']
            dataClass = list(Class.objects.filter(id=class_id).values())

            for m in dataClass:
                teacher_id = m['id_teacher_id']
                teacher_name = Teacher.objects.get(id=teacher_id).name

        for n in TEACHER:
            if n[0] == teacher_name:
                teacher = n[1]
        ###########################################################################

        # Cek ada data absensi ga
        if not Attendance.objects.filter(id_student=id).exists():
            raise Attendance.DoesNotExist
        ########################## buat data absensi################################

        dataAbsent = int(Attendance.objects.filter(
            id_student=id, status_attendance=0).values().count())
        dataPresent = int(Attendance.objects.filter(
            id_student=id, status_attendance=1).values().count())
        persentange_attendance = dataPresent / (dataAbsent+dataPresent)
        ###########################################################################

        # Cek ada data rate ga
        dataAttendance = list(Attendance.objects.filter(
            id_student=id).values_list('id', flat=True))

        dataRate = list(Rate.objects.values_list(
            'id_attendance', flat=True))

        def boolRate(dataRate, dataAttendance):
            for n in dataRate:
                if n in dataAttendance:
                    return True
            raise Rate.DoesNotExist
        boolRate(dataRate, dataAttendance)

        ########################## buat data rate #################################

        data = list(Attendance.objects.filter(
            id_student=id).values_list('id', flat=True))
        result = (list(Rate.objects.filter(
            id_attendance__in=data).values_list('rate', flat=True)))
        rate = round(statistics.mean(result))

        ml_model = joblib.load('ml_model/model3.joblib')
        result = ml_model.predict(
            [[distance, persentange_attendance, rate, teacher]])
        ###########################################################################

        for n in RESULT:
            if n[0] == result:
                resultML = n[1]
        return {'id': id, 'name': dataStudent.name, 'distance': distance, 'persentange_attendance': persentange_attendance*100, 'rate': rate, 'teacher': teacher_name, 'resultML': resultML}

    except Student.DoesNotExist:
        resultML = 'Please make student data'
        return {'id': id, 'name': dataStudent.name, 'resultML': resultML}
    except Attendance.DoesNotExist:
        resultML = "please make attendance data"
        return {'id': id, 'name': dataStudent.name, 'distance': distance, 'teacher': teacher_name, 'resultML': resultML}
    except Rate.DoesNotExist:
        resultML = "please make rate data"
        return {'id': id, 'name': dataStudent.name, 'distance': distance, 'persentange_attendance': persentange_attendance*100, 'teacher': teacher_name, 'resultML': resultML}


@login_required(login_url="User:login")
@permission_required('Predict.predict_all', login_url="permission_denied")
def choose(request):
    if request.method == "POST":
        data = request.POST.getlist('checkPresent')
        data = [int(item) for item in data]
        result = list()
        for n in data:
            result.append(prediction(n))
        # return JsonResponse(result, safe=False)
        return render(request, "../templates/predict/table_predict.html", {'form': result, 'choiceRate': CHOICESRATE, 'choiceDistance': CHOICEDISTANCE_AS_CATEGORIES})
    else:
        form = {
            'student': Student.objects.all(),
            'class': Class.objects.all(),
        }
        return render(request, "../templates/predict/list_predict.html", {'form': form})

P-S4/P1/templates/predict/list_predict.html
{% extends 'layout-blank.html' %}
{% block title %}
  {{ form.title }}
{% endblock %}
{% block content %}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Select Student to make Prediction</h4>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <form action="{% url 'Predict:choose'%}" method="post">
                        {% csrf_token %}
                        <table id="example" class="display" style="min-width: 845px">
                            <thead>
                                <tr>
                                <th scope="col">#</th>
                                <th scope="col">Name</th>
                                <th scope="col">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                    {% for data in form.student %}
                                    <tr>
                                        <th scope="row">{{ forloop.counter }}</th>
                                        <td>{{data.name}}</td>
                                        <td>        
                                            <div class="input-group">
                                                <input type="hidden" class="form-control" value="{{data.name}}">
                                                <input name="checkPresent" type="checkbox" class="btn-check" id="btn-check-2-outlined-{{data.id}}" value="{{data.id}}"autocomplete="off">
                                                <label class="btn btn-outline-success" for="btn-check-2-outlined-{{data.id}}">Present</label><br>
                                            </div>
                                        </td>
                                    </tr>
                                    {% endfor %}
                            </tbody>
                        </table>
                        <button class="btn btn-primary mb-3">submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
  </div>

<p>Created at {% now "Y-m-d H:i:s" %}</p>
<p>Created by <b>{{ request.user }}</b> </p>
{% endblock %}

P-S4/P1/templates/predict/table_predict.html
{% extends 'layout-blank.html' %}
{% load humanize %}
{% block title %}
  {{ form.title }}
{% endblock %}
{% block content %}
  {% comment %} <a href="{% url 'Schedule:create' %}">Create Data</a> {% endcomment %}

  <div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Predict Result</h4>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table id="example" class="display" style="min-width: 845px">
                        <thead>
                            <tr>
                              <th scope="col">#</th>
                              <th scope="col">Name</th>
                              <th scope="col">Teacher</th>
                              <th scope="col">Distance</th>
                              <th scope="col">Attendance (%)</th>
                              <th scope="col">Rate</th>
                              <th scope="col">Prediction</th>
                              {% comment %} <th scope="col">Action</th> {% endcomment %}
                            </tr>
                        </thead>
                        <tbody>

                          {% for data in form %}

                          <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ data.name}}</td>
                            <td>{{ data.teacher}}</td>
                  
                            {% for n in choiceDistance %}
                              {% if n.0 == data.distance %}
                                <td>{{ n.1}}</td>
                              {% endif %}
                            {% endfor %}
                            
                            
                            
                            {% if data.resultML == "please make attendance data" %}
                              <td colspan="3"class="table-danger" style="text-align: center;">{{data.resultML}}</td>
                            {% else  %}   
                              <td>{{ data.persentange_attendance|floatformat:"2" }}%</td>
                              {% if data.resultML == "please make rate data" %}
                                <td colspan="2"class="table-danger" style="text-align: center;">{{data.resultML}}</td>
                              {% else %}
                              {% for n in choiceRate %}
                                {% if n.0 == data.rate %}
                                  <td>{{ n.1}} </td>
                                {% endif %}
                              {% endfor %}
                              <td>{{ data.resultML }}</td>
                              {% endif %}
                            {% endif %}
                            {% comment %} <td> {% endcomment %}
                              {% comment %} <a href="{% url 'Schedule:read-detail' id=data.id %}">Detail Data</a> |
                              <a href="{% url 'Schedule:update' id=data.id %}">Update Data</a> |
                              <a href="{% url 'Schedule:delete' id=data.id %}" onclick="return confirm('Ingin Menghapus?')">Delete Data</a> {% endcomment %}
                            {% comment %} </td> {% endcomment %}
                          </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
  </div>
{% endblock %}