P-S4/P1/P1/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
urlpatterns = [
    path('', views.dashboard, name='home'),
    path('admin/', admin.site.urls),
    path('permission_denied/', views.permission_denied, name='permission_denied'),
    path('teacher/', include('Teacher.urls', namespace='teacher')),
    path('class/', include('Class.urls')),
    path('student/', include('Student.urls')),
    path('schedule/', include('Schedule.urls')),
    path('attendance/', include('Attendance.urls')),
    path('rate/', include('Rate.urls')),
    path('user/', include('User.urls')),
    path('predict/', include('Predict.urls')),
]

P-S4/P1/Schedule/urls.py
from django.urls import path, include
from . import views

app_name = "Schedule"
urlpatterns = [
    path('', views.read, name='read'),
    path('list_attendance/<slug:id>',
         views.list_attendance, name='list_attendance'),
    path('create', views.create, name='create'),
    path('update/<slug:id>', views.update, name='update'),
    path('delete/<slug:id>', views.delete, name='delete'),
    path('<slug:id>', views.readDetail, name='read-detail'),
]

P-S4/P1/Schedule/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.
from django.contrib.auth.models import User as U
# import joblib
from datetime import datetime
from Class.models import Class


class Schedule(models.Model):

    date = models.DateField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    class_id = models.ForeignKey(Class, on_delete=models.PROTECT)

    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(U, on_delete=models.PROTECT, default=None)

    def __str__(self):
        return str(self.date)

    def save(self, *args, **kwargs):

        # cek checkin dan checkout
        if self.check_in > self.check_out:
            # Swap check_in and check_out
            self.check_in, self.check_out = self.check_out, self.check_in

        return super().save(*args, *kwargs)

P-S4/P1/Schedule/forms.py
from django import forms
from . import models


class SaveForm(forms.ModelForm):

    class Meta:
        model = models.Schedule
        fields = ("date",
                  "check_in", "check_out", "class_id")

P-S4/P1/Schedule/views.py
# Create your views here.
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponse, JsonResponse
from django.contrib import messages
from .forms import SaveForm
from .models import Schedule, Class
from Student.models import Student
from Attendance.models import Attendance
from Attendance.views import createDataAttendance_Schedule, updateDataAttendance_Schedule
from django.forms.models import model_to_dict
import json
from django.core import serializers
# Create your views here.


def read(request):
    message = ""
    message_tag = ""
    for msg in messages.get_messages(request):
        message = msg
        message_tag = msg.tags
    form = {
        'title': 'View Data',
        'data': Schedule.objects.all(),
        "message": str(message),
        "message_tag": message_tag
    }

    return render(request, "../templates/schedule/read.html", {'form': form})

    # classs_list = list(Schedule.objects.all().values())

    # # Mengembalikan data dalam format JSON
    # return JsonResponse(classs_list, safe=False)


def readDetail(request, id):
    try:
        form = {
            'title': 'View Data',
            'data': Schedule.objects.get(id=id),
            'class': Class.objects.all(),
        }

        return render(request, "../templates/schedule/readDetail.html", {'form': form})
    except Exception as s:
        messages.error(request, s)
        return redirect("Schedule:read")


@login_required(login_url="User:login")
@permission_required('Schedule.add_schedule', login_url="permission_denied")
def create(request):
    if request.method == "POST":
        data = SaveForm(request.POST)
        if data.is_valid():
            data = data.save(commit=False)

            data.author = request.user
            data.save()
            student_with_class = list(Student.objects.filter(
                id_class=data.class_id).values())

            createDataAttendance_Schedule(
                request.user, data, *student_with_class)
            messages.success(request, "Data Berhasil dibuat")
            return redirect('Schedule:read')
        else:
            messages.error(request, data.errors)
            return redirect('Schedule:create')

    else:
        message = ""
        message_tag = ""
        for msg in messages.get_messages(request):
            message = msg
            message_tag = msg.tags
        form = {
            'title': 'Create Data',
            'form': SaveForm(),
            'class': Class.objects.all(),
            "message": str(message),
            "message_tag": message_tag
        }

        return render(request, "../templates/schedule/create.html", {'form': form})


@login_required(login_url="User:login")
@permission_required('Schedule.change_schedule', login_url="permission_denied")
def update(request, id):
    try:
        initialData = Schedule.objects.get(id=id)
        if request.method == "POST":
            data = SaveForm(request.POST, instance=initialData)
            if data.is_valid():
                data = data.save(commit=False)
                data.author = request.user
                data.save()
                messages.success(request, "Data Berhasil diubah")
                return redirect("Schedule:read")
            else:
                messages.error(request, data.errors)
                return redirect("Schedule:update")

        else:
            message = ""
            message_tag = ""
            for msg in messages.get_messages(request):
                message = msg
                message_tag = msg.tags

            form = {
                'title': 'Create Data',
                'form': SaveForm(instance=initialData),
                'class': Class.objects.all(),
                "message": str(message),
                "message_tag": message_tag
            }
            return render(request, "../templates/schedule/update.html", {'form': form})
    except Exception as s:
        messages.error(request, s)
        return redirect("Schedule:read")


@login_required(login_url="User:login")
@permission_required('Schedule.delete_schedule', login_url="permission_denied")
def delete(request, id):
    try:
        data = Schedule.objects.get(id=id)
        data.delete()
        messages.success(request, "Data Berhasil dihapus")
    except Exception as s:
        messages.error(request, s)
    return redirect("Schedule:read")


@login_required(login_url="User:login")
@permission_required('Attendance.list_attendance', login_url="permission_denied")
def list_attendance(request, id):
    initialData = Schedule.objects.get(id=id)
    if request.method == "POST":
        selected_names = None
        data = request.POST.getlist('checkPresent')
        # data = json.dumps(dict(request.POST.getlist('checkPresent')))
        # return JsonResponse(data, safe=False)
        updateDataAttendance_Schedule(request.user, id, *data)
        messages.success(request, "Data Attendance diubah")
        return redirect("Schedule:read")

    else:
        form = {
            'form': SaveForm(instance=initialData),
            'class': Class.objects.all(),
            # 'student_with_class': Student.objects.filter(
            #     id_class=Schedule.objects.get(id=id).class_id.id).values()
            'student_with_class': Attendance.objects.filter(id_schedule=id)
        }
    # data = list(data)
    # if not data:
    #     return HttpResponse("NOne")
    # return JsonResponse(data, safe=False)

    return render(request, "../templates/schedule/list_attendance.html", {'form': form})

P-S4/P1/templates/schedule/create.html
{% extends 'layout-blank.html' %}
{% block title %}
  {{ form.title }}
{% endblock %}
{% block content %}
  <form action="{% url 'Schedule:create' %}" method="post">
    {% csrf_token %}
    <label for="date">Date Birth:</label><br>
    <input type="date" id="date" name="date" class="form-control"  value="{{form.form.instance.date|date:'Y-m-d'}}" required autofocus ><br>
    <label for="check_in" class="col-sm-12 col-form-label">Check In</label>
    <input type="time" id="check_in" name="check_in" class="form-control"  value="{{ form.form.instance.check_in|time:'H:i'  }}" required/>
    <label for="check_out" class="col-sm-12 col-form-label">Check Out</label>
    <input type="time" id="check_out" name="check_out" class="form-control"  value="{{ form.form.instance.check_out|time:'H:i'  }}"required />
    <label for="class">Class:</label><br>
    <select id="class" name="class_id" class="form-control" required  >
      <option selected value="">------</option>
 
      {% for choice in form.class %} 
        {% if form.form.instance.class_id.id == choice.id %}
          <option value="{{ choice.id }}" selected>{{ choice.name }}</option>
        {% else %}
          <option value="{{ choice.id }}">{{ choice.name }}</option>
        {% endif %}
      {% endfor %}
    </select><br>

    <button class="btn btn-primary mb-3">submit</button>
  </form>
{% endblock %}

P-S4/P1/templates/schedule/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <form action="{% url 'Schedule:create' %}" method="post">
      {% csrf_token %}{{ form.as_p }}
      <button class="btn btn-primary mb-3">submit</button>
    </form>
  </body>
</html>

P-S4/P1/templates/schedule/list_attendance.html
{% extends 'layout-blank.html' %}
{% block title %}
  {{ form.title }}
{% endblock %}
{% block content %}
<form action="{% url 'Schedule:list_attendance' id=form.form.instance.id %}" method="post">
    {% csrf_token %}
        <label for="date">Date Birth:</label>
        <input type="date" id="date" name="date" class="form-control"  value="{{form.form.instance.date|date:'Y-m-d'}}" required disabled autofocus >
        <label for="check_in" class="col-sm-12 col-form-label">Check In</label>
        <input type="time" id="check_in" name="check_in" class="form-control"  value="{{ form.form.instance.check_in|time:'H:i'  }}" required disabled/>
        <label for="check_out" class="col-sm-12 col-form-label">Check Out</label>
        <input type="time" id="check_out" name="check_out" class="form-control"  value="{{ form.form.instance.check_out|time:'H:i'  }}"required disabled />
        <label for="class">Class:</label><br>
        <select id="class" name="class_id" class="form-control" required disabled  >
        <option selected value="">------</option>
    
        {% for choice in form.class %} 
            {% if form.form.instance.class_id.id == choice.id %}
            <option value="{{ choice.id }}" selected>{{ choice.name }}</option>
            {% else %}
            <option value="{{ choice.id }}">{{ choice.name }}</option>
            {% endif %}
        {% endfor %}
        </select><br>
        <div class="highlight">
            {% for data in form.student_with_class %}
            <div class="input-group">
                <input type="text" class="form-control" value="{{data.id_student.name}}">
                {% if  data.status_attendance == 1 %}
                <input name="checkPresent" type="checkbox" class="btn-check" id="btn-check-2-outlined-{{data.id_student.name}}" value="{{data.id}}"autocomplete="off" checked>
                {% else %}
                <input name="checkPresent" type="checkbox" class="btn-check" id="btn-check-2-outlined-{{data.id_student.name}}" value="{{data.id}}"autocomplete="off">
                {% endif %}
                <label class="btn btn-outline-success" for="btn-check-2-outlined-{{data.id_student.name}}">Present</label><br>
            </div>
            {% endfor %}
        </div>
        <p>Created at {{ form.data.date_created }}</p>
        <p>Last modify at {{ form.data.date_updated }}</p>
        <p>last modify by <b>{{ form.data.author }}</b> </p>
    <button class="btn btn-primary mb-3">submit</button>
</form>
{% endblock %}

P-S4/P1/templates/schedule/read.html
{% extends 'layout-blank.html' %}
{% block title %}
  {{ form.title }}
{% endblock %}
{% block content %}
  <a href="{% url 'Schedule:create' %}">Create Data</a>
  <table class="table">
  <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Class</th>
        <th scope="col">Date</th>
        <th scope="col">Check In</th>
        <th scope="col">Check Out</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      {% for data in form.data %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{ data.class_id.name }}</td>
          <td>{{ data.date|date:'Y-m-d' }}</td>
          <td>{{ data.check_in|time:'H:i' }}</td>
          <td>{{ data.check_out|time:'H:i' }}</td>
          <td>
            <a href="{% url 'Schedule:list_attendance' id=data.id %}">Attendance</a> |
            <a href="{% url 'Schedule:read-detail' id=data.id %}">Detail Data</a> |
            <a href="{% url 'Schedule:update' id=data.id %}">Update Data</a> |
            <a href="{% url 'Schedule:delete' id=data.id %}" onclick="return confirm('Ingin Menghapus?')">Delete Data</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

P-S4/P1/templates/schedule/readDetail.html
{% extends 'layout-blank.html' %}
{% block title %}
  {{ form.title }}
{% endblock %}
{% block content %}
    <label for="date">Date Birth:</label>
    <input type="date" id="date" name="date" class="form-control"  value="{{form.data.date|date:'Y-m-d'}}" required disabled autofocus >
    <label for="check_in" class="col-sm-12 col-form-label">Check In</label>
    <input type="time" id="check_in" name="check_in" class="form-control"  value="{{ form.data.check_in|time:'H:i'  }}" required disabled/>
    <label for="check_out" class="col-sm-12 col-form-label">Check Out</label>
    <input type="time" id="check_out" name="check_out" class="form-control"  value="{{ form.data.check_out|time:'H:i'  }}"required disabled />
    <label for="class">Class:</label><br>
    <select id="class" name="class_id" class="form-control" required disabled  >
      <option selected value="">------</option>
 
      {% for choice in form.class %} 
        {% if form.data.class_id.id == choice.id %}
          <option value="{{ choice.id }}" selected>{{ choice.name }}</option>
        {% else %}
          <option value="{{ choice.id }}">{{ choice.name }}</option>
        {% endif %}
      {% endfor %}
    </select><br>


    <p>Created at {{ form.data.date_created }}</p>
    <p>Last modify at {{ form.data.date_updated }}</p>
    <p>last modify by <b>{{ form.data.author }}</b> </p>
       
{% endblock %}

P-S4/P1/templates/schedule/update.html
{% extends 'layout-blank.html' %}
{% block title %}
  {{ form.title }}
{% endblock %}
{% block content %}
  <form action="{% url 'Schedule:update' id=form.form.instance.id %}" method="post">
    {% csrf_token %}
    <label for="date">Date Birth:</label><br>
    <input type="date" id="date" name="date" class="form-control"  value="{{form.form.instance.date|date:'Y-m-d'}}" required autofocus ><br>
    <label for="check_in" class="col-sm-12 col-form-label">Check In</label>
    <input type="time" id="check_in" name="check_in" class="form-control"  value="{{ form.form.instance.check_in|time:'H:i'  }}" required/>
    <label for="check_out" class="col-sm-12 col-form-label">Check Out</label>
    <input type="time" id="check_out" name="check_out" class="form-control"  value="{{ form.form.instance.check_out|time:'H:i'  }}"required />
    <label for="class">Class:</label><br>
    <select id="class" name="class_id" class="form-control" required  >
      <option selected value="">------</option>
 
      {% for choice in form.class %} 
        {% if form.form.instance.class_id.id == choice.id %}
          <option value="{{ choice.id }}" selected>{{ choice.name }}</option>
        {% else %}
          <option value="{{ choice.id }}">{{ choice.name }}</option>
        {% endif %}
      {% endfor %}
    </select><br>

    
    <button class="btn btn-primary mb-3">submit</button>
  </form>
{% endblock %}