P-S4/P1/Attendance/urls.py
from django.urls import path, include
from . import views

app_name = "Attendance"
urlpatterns = [
    path('', views.read, name='read'),
    # path('list_attendance/<slug:id>',
    #      views.list_attendance, name='list_attendance'),
    # path('create', views.create, name='create'),
    path('update/<slug:id>', views.update, name='update'),
    path('delete/<slug:id>', views.delete, name='delete'),
    path('<slug:id>', views.readDetail, name='read-detail'),
]

P-S4/P1/Class/urls.py
from django.urls import path, include
from . import views

app_name = "Class"
urlpatterns = [
    path('', views.read, name='read'),
    path('create', views.create, name='create'),
    path('update/<slug:id>', views.update, name='update'),
    path('delete/<slug:id>', views.delete, name='delete'),
    path('<slug:id>', views.readDetail, name='read-detail'),
]

P-S4/P1/P1/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
urlpatterns = [
    path('', views.dashboard, name='home'),
    path('admin/', admin.site.urls),
    path('permission_denied/', views.permission_denied, name='permission_denied'),
    path('teacher/', include('Teacher.urls', namespace='teacher')),
    path('class/', include('Class.urls')),
    path('student/', include('Student.urls')),
    path('schedule/', include('Schedule.urls')),
    path('attendance/', include('Attendance.urls')),
    path('rate/', include('Rate.urls')),
    path('user/', include('User.urls')),
    path('predict/', include('Predict.urls')),
]

P-S4/P1/Rate/urls.py
from django.urls import path, include
from . import views

app_name = "Rate"
urlpatterns = [
    path('', views.read, name='read'),
    # path('list_attendance/<slug:id>',
    #      views.list_attendance, name='list_attendance'),
    # path('create', views.create, name='create'),
    path('create_attendance', views.createDataRate_Attendance,
         name='create_attendance'),
    path('update/<slug:id>', views.update, name='update'),
    path('delete/<slug:id>', views.delete, name='delete'),
    path('<slug:id>', views.readDetail, name='read-detail'),
]

P-S4/P1/Attendance/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.
from django.contrib.auth.models import User as U
from Student.models import Student
from Schedule.models import Schedule

CHOICESATTENDACE = [(0, 'Absent'), (1, 'Present')]


class Attendance(models.Model):

    id_schedule = models.ForeignKey(Schedule, on_delete=models.PROTECT)
    id_student = models.ForeignKey(Student, on_delete=models.PROTECT)
    status_attendance = models.PositiveIntegerField(choices=CHOICESATTENDACE)

    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(U, on_delete=models.PROTECT, default=None)

    def __str__(self):
        return str(self.id_schedule.date)

    class Meta:
        # Definisikan kombinasi unik dari tabel_a dan tabel_b untuk mencegah duplikat
        unique_together = ('id_schedule', 'id_student')
        default_permissions = ('add', 'change', 'delete')
        permissions = (
            ('list_attendance', 'can update list attendance'),
        )

P-S4/P1/Attendance/forms.py
from django import forms
from . import models


class SaveForm(forms.ModelForm):

    class Meta:
        model = models.Attendance
        fields = ("id_schedule", "id_student", "status_attendance")

P-S4/P1/Attendance/views.py
# Create your views here.
from django import template
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponse, JsonResponse
from django.contrib import messages
from .forms import SaveForm
from .models import Attendance, Schedule, Student, CHOICESATTENDACE
from Rate.models import Rate, CHOICESRATE
# Create your views here.

register = template.Library()


def read(request):
    message = ""
    message_tag = ""
    for msg in messages.get_messages(request):
        message = msg
        message_tag = msg.tags
    # data = Attendance.objects.all()
    # for n in data:
    #     n['newData'] = 1
    # data = list(data.values())
    listRate = [list(Rate.objects.all().values_list(
        'id_attendance', flat=True))][0]
    form = {
        'title': 'View Data',
        'data': Attendance.objects.all(),
        'status': CHOICESATTENDACE,
        'rate': Rate.objects.all(),
        'choiceRate': CHOICESRATE,
        'list': listRate,
        "message": str(message),
        "message_tag": message_tag
    }

    return render(request, "../templates/attendance/read.html", {'form': form})

    # classs_list = list(Attendance.objects.all().values())

    # # Mengembalikan data dalam format JSON
    # return JsonResponse(classs_list, safe=False)


def readDetail(request, id):
    try:
        form = {
            'title': 'View Data',
            'data': Attendance.objects.get(id=id),
            'schedule': Schedule.objects.all(),
            'student': Student.objects.all(),
            'status': CHOICESATTENDACE,
        }

        return render(request, "../templates/attendance/readDetail.html", {'form': form})
    except Exception as s:
        messages.error(request, s)
        return redirect("Attendance:read")


@login_required(login_url="User:login")
@permission_required('Attendance.add_attendance', login_url="permission_denied")
def create(request):
    if request.method == "POST":
        data = SaveForm(request.POST)
        if data.is_valid():
            data = data.save(commit=False)
            data.author = request.user
            data.save()
            messages.success(request, "Data Berhasil dibuat")
            return redirect('Attendance:read')
        else:
            messages.error(request, data.errors)
            return redirect('Attendance:create')

    else:
        message = ""
        message_tag = ""
        for msg in messages.get_messages(request):
            message = msg
            message_tag = msg.tags
        form = {
            'title': 'Create Data',
            'form': SaveForm(),
            'schedule': Schedule.objects.all(),
            'student': Student.objects.all(),
            'status': CHOICESATTENDACE,
            "message": str(message),
            "message_tag": message_tag
        }

        return render(request, "../templates/attendance/create.html", {'form': form})


@login_required(login_url="User:login")
@permission_required('Attendance.change_attendance', login_url="permission_denied")
def update(request, id):
    try:
        initialData = Attendance.objects.get(id=id)
        if request.method == "POST":
            data = SaveForm(request.POST, instance=initialData)
            if data.is_valid():
                data = data.save(commit=False)
                data.author = request.user
                data.save()
                messages.success(request, "Data Berhasil diubah")
                return redirect("Attendance:read")
            else:
                messages.error(request, data.errors)
                return redirect("Attendance:update")

        else:
            message = ""
            message_tag = ""
            for msg in messages.get_messages(request):
                message = msg
                message_tag = msg.tags

            form = {
                'title': 'Create Data',
                'form': SaveForm(instance=initialData),
                'schedule': Schedule.objects.all(),
                'student': Student.objects.all(),
                'status': CHOICESATTENDACE,
                "message": str(message),
                "message_tag": message_tag
            }
            return render(request, "../templates/attendance/update.html", {'form': form})
    except Exception as s:
        messages.error(request, s)
        return redirect("Attendance:read")


def delete(request, id):
    try:
        data = Attendance.objects.get(id=id)
        data.delete()
        messages.success(request, "Data Berhasil dihapus")
    except Exception as s:
        messages.error(request, s)
    return redirect("Attendance:read")


def createDataAttendance_Schedule(user, dataSchedule, *data):
    # data = SaveForm(request.POST)
    # if data.is_valid():
    #     data = data.save(commit=False)
    #     data.author = request.user
    #     data.save()
    #     messages.success(request, "Data Berhasil dibuat")
    #     return redirect('Attendance:read')
    for n in data:
        data = Attendance()
        data.id_schedule = dataSchedule
        dataStudent = Student.objects.get(id=n['id'])
        data.id_student = dataStudent
        data.status_attendance = 0
        data.author = user
        data.save()


def updateDataAttendance_Schedule(user, id_schedule, *data):
    data = [int(item) for item in data]
    for n in data:
        checkData = Attendance.objects.get(id=n)
        if (checkData.status_attendance == 0):
            checkData.status_attendance = 1
            checkData.author = user
            checkData.save()
            # change status_attendance to 1

    checkData = Attendance.objects.filter(
        status_attendance=1, id_schedule=id_schedule)

    for n in checkData:
        if (n.status_attendance == 1) and (n.id not in data):
            # change status_attendance to 0
            n.status_attendance = 0
            n.save()

P-S4/P1/templates/attendance/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <form action="{% url 'Attendance:create' %}" method="post">
      {% csrf_token %}{{ form }}
      <button class="btn btn-primary mb-3">submit</button>
    </form>
  </body>
</html>

P-S4/P1/templates/attendance/read.html
{% extends 'layout-blank.html' %}

{% block title %}
  {{ form.title }}
{% endblock %}
{% block content %}
  {% comment %} <a href="{% url 'Attendance:create' %}">Create Data</a> {% endcomment %}
  <table class="table">
  <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Schedule</th>
        <th scope="col">Student</th>
        <th scope="col">Status Attendance</th>
        <th scope="col">Action</th>
        <th scope="col">Rating</th>
      </tr>
    </thead>
    <tbody>
      {% for data in form.data %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{ data.id_schedule.date }}</td>
          <td>{{ data.id_student.name }}</td>
          
          {% for choice in form.status %} 
            {% if data.status_attendance == choice.0 %}
              <td>{{ choice.1 }}</td>
            {% endif %}
          {% endfor %}
          <td>
          
          <a href="{% url 'Attendance:read-detail' id=data.id %}">Detail Data</a> |
            <a href="{% url 'Attendance:update' id=data.id %}">Update Data</a> |
            <a href="{% url 'Attendance:delete' id=data.id %}" onclick="return confirm('Ingin Menghapus?')">Delete Data</a>
          </td>
       
          <!-- Modal -->
          <td>
            {% if data.id in form.list %}
              {% for choice in form.rate %}
                {% if choice.id_attendance_id == data.id %}
                  {% for choiceRate in form.choiceRate %}
                    {% if choice.rate == choiceRate.0 %}
                        {{ choiceRate.1 }}
                    {% endif %}
                  {% endfor %}
                {% endif %}
              {% endfor %}
            {% else %} 
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#staticBackdrop{{data.id}}">
              Rate Me
            </button>
            <div class="modal fade" id="staticBackdrop{{data.id}}" >
              <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h1 class="modal-title fs-5" id="staticBackdropLabel">Modal title</h1>
                    <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <form action="{% url 'Rate:create_attendance' %}" method="post">
                    {% csrf_token %}
                    <div class="modal-body">
                      <input type="text" name='id_attendance' value="{{data.id}}" hidden>
                      <label for="selectRating">rating</label>
                      <select name="rate" class="form-control" id="selectRating" required>
                        <option value="">-------</option>
                        {% for choice in form.choiceRate %}
                        <option value="{{choice.0}}">{{choice.1}}</option>
                        {% endfor %}
                      </select>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                      <button class="btn btn-primary">Submit</button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          {% endif %}
            {% comment %} {% for choice in form.rate %}
                {% if choice.id_attendance_id == data.id %}
                    {% for choiceRate in form.choiceRate %}
                        {% if choice.rate == choiceRate.0 %}
                            {{ choiceRate.1 }}
                        {% endif %}
                    {% endfor %}
                {% endif %}
            {% endfor %} {% endcomment %}

            
          </td>
       
          
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

P-S4/P1/templates/attendance/readDetail.html
{% extends 'layout-blank.html' %}
{% block title %}
  {{ form.title }}
{% endblock %}
{% block content %}

    <label for="schedule">Schedule:</label><br>
    <select id="schedule" name="id_schedule" class="form-control" required disabled autofocus >
    <option selected value="">------</option>

    {% for choice in form.schedule %} 
        {% if form.data.id_schedule.id == choice.id %}
        <option value="{{ choice.id }}" selected>{{ choice.date }}</option>
        {% else %}
        <option value="{{ choice.id }}">{{ choice.date }}</option>
        {% endif %}
    {% endfor %}
    </select><br>

    <label for="student">Student:</label><br>
    <select id="student" name="id_student" class="form-control" required  disabled>
      <option selected value="">------</option>

      {% for choice in form.student %} 
        {% if form.data.id_student.id == choice.id %}
          <option value="{{ choice.id }}" selected>{{ choice.name }}</option>
        {% else %}
          <option value="{{ choice.id }}">{{ choice.name }}</option>
        {% endif %}
      {% endfor %}
    </select><br>

    <label for="status">Status Attendance:</label><br>
    <select id="status" name="status_attendance" class="form-control" required disabled >
      <option selected value="">------</option>

      {% for choice in form.status %} 
        {% if form.data.status_attendance == choice.0 %}
          <option value="{{ choice.0 }}" selected>{{ choice.1 }}</option>
        {% else %}
          <option value="{{ choice.0 }}">{{ choice.1 }}</option>
        {% endif %}
      {% endfor %}
    </select><br>

    <p>Created at {{ form.data.date_created }}</p>
    <p>Last modify at {{ form.data.date_updated }}</p>
    <p>last modify by <b>{{ form.data.author }}</b> </p>
       
{% endblock %}

P-S4/P1/templates/attendance/update.html
{% extends 'layout-blank.html' %}
{% block title %}
  {{ form.title }}
{% endblock %}
{% block content %}
  <form action="{% url 'Attendance:update' id=form.form.instance.id %}" method="post">
    {% csrf_token %}
    <label for="schedule">Schedule:</label><br>
    <select id="schedule" name="id_schedule" class="form-control" required  autofocus >
    <option selected value="">------</option>
    
    {% for choice in form.schedule %} 
        {% if form.form.instance.id_schedule.id == choice.id %}
        <option value="{{ choice.id }}" selected>{{ choice.date }}</option>
        {% else %}
        <option value="{{ choice.id }}">{{ choice.date }}</option>
        {% endif %}
    {% endfor %}
    </select><br>
    
    <label for="student">Student:</label><br>
    <select id="student" name="id_student" class="form-control" required  >
      <option selected value="">------</option>
 
      {% for choice in form.student %} 
        {% if form.form.instance.id_student.id == choice.id %}
          <option value="{{ choice.id }}" selected>{{ choice.name }}</option>
        {% else %}
          <option value="{{ choice.id }}">{{ choice.name }}</option>
        {% endif %}
      {% endfor %}
    </select><br>

    <label for="status">Status Attendance:</label><br>
    <select id="status" name="status_attendance" class="form-control" required  >
      <option selected value="">------</option>
 
      {% for choice in form.status %} 
        {% if form.form.instance.status_attendance == choice.0 %}
          <option value="{{ choice.0 }}" selected>{{ choice.1 }}</option>
        {% else %}
          <option value="{{ choice.0 }}">{{ choice.1 }}</option>
        {% endif %}
      {% endfor %}
    </select><br>
    
    
    <button class="btn btn-primary mb-3">submit</button>
  </form>
{% endblock %}